import type { Lang } from './data'

/* Ghi chú kỹ thuật — chỉ những gì đã đối chiếu trong mã nguồn */

export interface How { label: string; title: string; intro: string; notes: string[]; toolsLabel: string; tools: [string, string][] }

export const tech: Record<Lang, Record<string, string[]>> = {
  vi: {
    tieu: [
      'Flutter với Provider, khoảng 20.000 dòng Dart chia 10 module',
      'Từ điển nằm trong SQLCipher AES-256; âm thanh mã hoá AES-GCM trong container KXA1 tự định nghĩa, tên file ràng buộc làm AAD',
      'Một khoá gốc tách thành hai mảnh XOR, HKDF-SHA256 sinh khoá riêng cho cơ sở dữ liệu và âm thanh',
      'Pipeline Python năm bước: dữ liệu thô → ngữ pháp → hội thoại → SQLite → mã hoá; đây là đường build duy nhất lên store',
      'Script kiểm tra bảo mật mở file IPA/AAB đã build, thấy SQLite hay MP3 chưa mã hoá là chặn phát hành',
      'Supabase cho cộng đồng, gói nội dung OTA tải qua URL ký có hạn 10 phút',
    ],
    meal: [
      'Flutter với GetX, dữ liệu offline trong sqflite',
      'StoreKit 2 trực tiếp, không RevenueCat: app gửi JWS của Apple lên Cloudflare Worker, Worker đối chiếu với root CA của Apple rồi mới ghi sổ',
      'Sổ giao dịch và tín dụng AI trong D1, hạn mức trong KV; giao dịch chỉ kết thúc sau khi D1 xác nhận',
      'Tín dụng AI được giữ chỗ phía server và chỉ trừ khi thao tác thành công; luồng offline không bao giờ tốn tín dụng',
      'Nếu thiếu cấu hình proxy trong bản phát hành, thanh toán đóng lại nhưng toàn bộ tính năng offline vẫn chạy',
      'Script release_audit chạy 12 cửa kiểm tra: phân tích, unit test, dữ liệu offline, smoke test proxy, privacy manifest, metadata',
    ],
    drop: [
      'Flutter với GetX: 193 file Dart, khoảng 45.000 dòng, 31 màn hình',
      'Firebase Auth (Google, Apple), Firestore với rules và index kèm trong repo, App Check, Crashlytics',
      'Backend media riêng bằng Python trên Render, xác thực bằng Firebase ID token, giới hạn 15 MB mỗi ảnh',
      'Fastlane tạo sản phẩm IAP và giá theo quốc gia trên Play Console bằng code thay vì bấm tay',
      'Repository trả về Result/Failure thay vì ném exception',
      'Ảnh chứng minh nén ngay trên máy; chia sẻ riêng tư qua mã QR',
    ],
    pea: [
      'SwiftUI, khoảng 12.000 dòng Swift; XcodeGen sinh project với 7 target',
      'Bốn app extension: DeviceActivityMonitor, ShieldConfiguration, ShieldAction và Widget (WidgetKit + Live Activity)',
      'Shield được bật hai lần, trong app và từ extension, vì intervalDidStart có thể trễ vài giây',
      'Trạng thái dùng chung qua App Group và JSON, không CoreData, vì extension chỉ có khoảng 6 MB bộ nhớ',
      'Backend Go chỉ dùng net/http và SQLite thuần Go, một image khoảng 15 MB trên Fly.io',
      'Tự xác thực App Store Server Notifications v2 bằng thư viện chuẩn; đồng hồ nhảy quá 5 phút thì phiên bị coi là bỏ dở',
    ],
    nuni: [
      'Go 1.26 với chi và pgx trên PostgreSQL, khoảng 30.000 dòng, hơn 20 migration goose',
      'Web Next.js 16 và React 19 với 56 route; app Flutter với flutter_bloc, khoảng 45.000 dòng',
      'Lịch ôn tập FSRS thay vì SM-2; autosave kiểu CAS với nộp bài idempotent, có E2E mô phỏng hai thiết bị',
      'Design token và asset sinh ra cho cả React lẫn Dart, bước verify thất bại nếu hai bên lệch nhau',
      'Mỗi bản phát hành kèm verification.json ghi log test và hash build',
      'Prometheus cho metrics, MinIO cho file, Firebase Admin cho xác thực',
    ],
    crab: [
      'Node/Express trên MongoDB; JWT kết hợp bảng key-token xoay theo thiết bị',
      'Ngày làm việc tính từ 6 giờ sáng đến 6 giờ sáng hôm sau theo giờ Việt Nam, xuyên suốt mọi báo cáo',
      'Tự sao lưu phía MongoDB trước mọi thao tác xoá; bảng tham chiếu không bao giờ bị xoá',
      'Module analytics tách rời, xuất báo cáo HTML, Excel và Word từ cùng cơ sở dữ liệu',
      'Hai app Flutter với GetX: một cho người đứng cân, một cho quản trị',
    ],
  },
  en: {
    tieu: [
      'Flutter with Provider, about 20,000 lines of Dart across 10 modules',
      'Dictionary in SQLCipher AES-256; audio encrypted with AES-GCM in a custom KXA1 container, filename bound as AAD',
      'One master key split into two XOR shares; HKDF-SHA256 derives separate keys for the database and the audio',
      'Five-step Python pipeline: raw data → grammar → dialogues → SQLite → encryption; the only sanctioned path to a store build',
      'A security audit opens the built IPA/AAB and fails the release if it finds unencrypted SQLite or MP3',
      'Supabase for the community; OTA content packs served through 10-minute signed URLs',
    ],
    meal: [
      'Flutter with GetX, offline data in sqflite',
      'StoreKit 2 directly, no RevenueCat: the app sends Apple\'s JWS to a Cloudflare Worker, which checks it against Apple\'s root CAs before recording it',
      'Transaction and AI-credit ledgers in D1, quotas in KV; a purchase is only finished after D1 accepts it',
      'AI credits are reserved server-side and charged only on success; offline flows never spend credits',
      'If the proxy config is missing in a release build, payments fail closed while every offline feature keeps working',
      'A release_audit script runs 12 gates: analysis, unit tests, offline data, proxy smoke tests, privacy manifest, metadata',
    ],
    drop: [
      'Flutter with GetX: 193 Dart files, about 45,000 lines, 31 screens',
      'Firebase Auth (Google, Apple), Firestore with rules and indexes checked in, App Check, Crashlytics',
      'A separate Python media backend on Render, authenticated with Firebase ID tokens, 15 MB per upload',
      'Fastlane provisions Play Console IAP products and per-country prices from code instead of by hand',
      'Repositories return Result/Failure values instead of throwing',
      'Proof photos are compressed on device; private sharing works over QR codes',
    ],
    pea: [
      'SwiftUI, about 12,000 lines of Swift; XcodeGen generates a 7-target project',
      'Four app extensions: DeviceActivityMonitor, ShieldConfiguration, ShieldAction and a Widget (WidgetKit + Live Activity)',
      'The shield is armed twice, in-app and from the extension, because intervalDidStart can lag by seconds',
      'Shared state via App Group and JSON, no CoreData, because extensions get roughly 6 MB of memory',
      'A Go backend on net/http and pure-Go SQLite, one ~15 MB image on Fly.io',
      'App Store Server Notifications v2 verified with the standard library; a clock jump over 5 minutes marks a session abandoned',
    ],
    nuni: [
      'Go 1.26 with chi and pgx on PostgreSQL, about 30,000 lines, 20+ goose migrations',
      'Next.js 16 and React 19 web with 56 routes; a Flutter app on flutter_bloc, about 45,000 lines',
      'FSRS scheduling instead of SM-2; CAS-based autosave with idempotent submissions, exercised by a two-device E2E script',
      'Design tokens and assets generated into both React and Dart, with a verify step that fails on drift',
      'Every release ships with a verification.json recording test logs and build hashes',
      'Prometheus for metrics, MinIO for files, Firebase Admin for auth',
    ],
    crab: [
      'Node/Express on MongoDB; JWT paired with a per-device rotating key-token table',
      'The business day runs 06:00 to 06:00 Vietnam time, honoured across every report',
      'An automatic MongoDB-side backup before any delete; reference collections can never be deleted',
      'A decoupled analytics module renders HTML, Excel and Word reports from the same database',
      'Two Flutter apps on GetX: one for the scale operator, one for the owner',
    ],
  },
  zh: {
    tieu: [
      'Flutter 与 Provider，约 20,000 行 Dart，分 10 个模块',
      '词典存于 SQLCipher AES-256；音频用 AES-GCM 加密，封装在自定义的 KXA1 容器中，文件名作为 AAD 绑定',
      '一把主密钥拆成两份 XOR 分片；HKDF-SHA256 分别派生数据库密钥和音频密钥',
      '五步 Python 流水线：原始数据 → 语法 → 对话 → SQLite → 加密；这是上架构建的唯一路径',
      '安全审计脚本会打开构建好的 IPA/AAB，发现未加密的 SQLite 或 MP3 就阻止发布',
      '社区功能用 Supabase；OTA 内容包通过 10 分钟有效期的签名链接下发',
    ],
    meal: [
      'Flutter 与 GetX，离线数据存于 sqflite',
      '直接使用 StoreKit 2，不用 RevenueCat：应用把 Apple 的 JWS 发到 Cloudflare Worker，Worker 用 Apple 根证书校验后才记账',
      '交易账本和 AI 额度存在 D1，配额存在 KV；D1 确认之后交易才算完成',
      'AI 额度在服务端预留，只有操作成功才扣除；离线流程永远不消耗额度',
      '正式版若缺少代理配置，支付会关闭，但全部离线功能照常可用',
      'release_audit 脚本跑 12 道关卡：静态分析、单元测试、离线数据、代理冒烟测试、隐私清单、商店元数据',
    ],
    drop: [
      'Flutter 与 GetX：193 个 Dart 文件，约 45,000 行，31 个页面',
      'Firebase Auth（Google、Apple）、Firestore（规则和索引随仓库提交）、App Check、Crashlytics',
      '独立的 Python 媒体后端部署在 Render，用 Firebase ID token 鉴权，单次上传上限 15 MB',
      '用 Fastlane 以代码方式在 Play Console 创建内购商品和分国家定价，而不是手动点',
      'Repository 返回 Result/Failure，而不是抛异常',
      '打卡照片在设备上压缩；私密分享通过二维码完成',
    ],
    pea: [
      'SwiftUI，约 12,000 行 Swift；用 XcodeGen 生成含 7 个 target 的工程',
      '四个 App Extension：DeviceActivityMonitor、ShieldConfiguration、ShieldAction 和 Widget（WidgetKit + Live Activity）',
      '屏蔽会启用两次——应用内一次、扩展内一次——因为 intervalDidStart 可能延迟数秒',
      '共享状态走 App Group 加 JSON，不用 CoreData，因为扩展只有约 6 MB 内存',
      'Go 后端只用 net/http 和纯 Go 的 SQLite，一个约 15 MB 的镜像跑在 Fly.io',
      '用标准库自行校验 App Store Server Notifications v2；时钟跳动超过 5 分钟即判定专注会话中断',
    ],
    nuni: [
      'Go 1.26，chi 与 pgx 配合 PostgreSQL，约 30,000 行，20 多个 goose 迁移',
      '网页端 Next.js 16 与 React 19，56 个路由；Flutter 应用基于 flutter_bloc，约 45,000 行',
      '复习调度用 FSRS 而非 SM-2；CAS 式自动保存加幂等提交，并有模拟双设备的端到端脚本',
      '设计令牌和资源同时生成到 React 和 Dart，校验步骤在两边不一致时直接失败',
      '每个版本附带 verification.json，记录测试日志和构建哈希',
      'Prometheus 负责指标，MinIO 负责文件，Firebase Admin 负责鉴权',
    ],
    crab: [
      'Node/Express 配 MongoDB；JWT 加按设备轮换的 key-token 表',
      '营业日按越南时间早上 6 点到次日 6 点计算，所有报表统一遵守',
      '任何删除操作前都会在 MongoDB 侧自动备份；基础参照表永远不可删除',
      '独立的 analytics 模块从同一数据库生成 HTML、Excel 和 Word 报表',
      '两个基于 GetX 的 Flutter 应用：一个给称重员，一个给老板',
    ],
  },
}

export const how: Record<Lang, How> = {
  vi: {
    label: 'Cách tôi làm',
    title: 'Vài quyết định kỹ thuật tôi *thấy đáng kể*.',
    intro: 'Mỗi dòng dưới đây là một thứ có thật trong mã nguồn, không phải khẩu hiệu.',
    notes: [
      'Từ điển trong SQLCipher AES-256; âm thanh AES-GCM, tên file ràng buộc làm AAD.',
      'Khoá gốc tách hai mảnh XOR; HKDF sinh khoá riêng cho dữ liệu và âm thanh.',
      'Build phát hành tự thất bại nếu còn SQLite hay MP3 chưa mã hoá trong IPA.',
      'Chuỗi chứng chỉ JWS của Apple xác thực bằng thư viện chuẩn Go, không thêm dependency.',
      'Shield của Screen Time bật hai lần, trong app và từ extension, để không lỡ giây nào.',
      'Extension chặn app giữ dưới 6 MB: không StoreKit, không quảng cáo, không mạng.',
      'Đồng hồ máy nhảy quá năm phút thì phiên tập trung bị coi là bỏ dở.',
      'Biên nhận StoreKit 2 được Worker xác thực, ghi sổ D1, rồi mới kết thúc giao dịch.',
      'Tín dụng AI giữ chỗ phía server, chỉ trừ khi thao tác thành công.',
      'Lịch ôn tập FSRS viết bằng Go; autosave kiểu CAS giữ hai thiết bị nhất quán.',
      'Design token sinh ra cho cả React lẫn Dart; CI thất bại nếu hai bên lệch.',
      'Fastlane tạo sản phẩm IAP và giá theo quốc gia trên Play Console bằng code.',
    ],
    toolsLabel: 'Bộ công cụ',
    tools: [
      ['Mobile', 'Flutter (GetX, Provider, BLoC), SwiftUI, WidgetKit, Screen Time API'],
      ['Backend', 'Go (net/http, chi, pgx), Node/Express, Cloudflare Workers'],
      ['Dữ liệu', 'PostgreSQL, SQLite/SQLCipher, Firestore, Supabase, MongoDB, D1/KV'],
      ['Thanh toán', 'StoreKit 2, App Store Server Notifications v2, Google Play Billing'],
      ['Phát hành', 'XcodeGen, Fastlane, script kiểm tra tự viết, Fly.io, Render, Docker'],
    ],
  },
  en: {
    label: 'How I build',
    title: 'A few engineering decisions *I stand behind*.',
    intro: 'Every line below is something real in the source, not a slogan.',
    notes: [
      'Dictionary in SQLCipher AES-256; audio in AES-GCM with the filename bound as AAD.',
      'Master key split into two XOR shares; HKDF derives separate data and audio keys.',
      'The release build fails if unencrypted SQLite or MP3 survives in the IPA.',
      'Apple\'s JWS certificate chain verified with the Go standard library, no extra dependency.',
      'The Screen Time shield is armed twice, in-app and from the extension, so no second is lost.',
      'The blocking extension stays under 6 MB: no StoreKit, no ads, no networking.',
      'A clock jump over five minutes marks a focus session abandoned.',
      'StoreKit 2 receipts are verified by a Worker and written to D1 before the transaction finishes.',
      'AI credits are reserved server-side and charged only when the action succeeds.',
      'FSRS scheduling in Go; CAS autosave keeps two devices consistent.',
      'Design tokens generated into both React and Dart; CI fails on drift.',
      'Fastlane provisions Play Console IAP products and per-country prices from code.',
    ],
    toolsLabel: 'Toolbox',
    tools: [
      ['Mobile', 'Flutter (GetX, Provider, BLoC), SwiftUI, WidgetKit, Screen Time API'],
      ['Backend', 'Go (net/http, chi, pgx), Node/Express, Cloudflare Workers'],
      ['Data', 'PostgreSQL, SQLite/SQLCipher, Firestore, Supabase, MongoDB, D1/KV'],
      ['Payments', 'StoreKit 2, App Store Server Notifications v2, Google Play Billing'],
      ['Release', 'XcodeGen, Fastlane, hand-written audit scripts, Fly.io, Render, Docker'],
    ],
  },
  zh: {
    label: '我怎么做',
    title: '几个我*站得住脚*的技术决定。',
    intro: '下面每一条都真实存在于代码里，不是口号。',
    notes: [
      '词典存于 SQLCipher AES-256；音频用 AES-GCM，文件名作为 AAD 绑定。',
      '主密钥拆成两份 XOR 分片；HKDF 分别派生数据密钥和音频密钥。',
      'IPA 里若残留未加密的 SQLite 或 MP3，发布构建直接失败。',
      '用 Go 标准库校验 Apple 的 JWS 证书链，不引入额外依赖。',
      'Screen Time 屏蔽启用两次——应用内和扩展内——一秒都不漏。',
      '屏蔽扩展保持在 6 MB 以下：没有 StoreKit，没有广告，没有网络。',
      '系统时钟跳动超过五分钟，专注会话即判定为中断。',
      'StoreKit 2 收据先由 Worker 校验并写入 D1，交易才算完成。',
      'AI 额度在服务端预留，只有操作成功才扣除。',
      '用 Go 实现 FSRS 复习调度；CAS 式自动保存让两台设备保持一致。',
      '设计令牌同时生成到 React 和 Dart；两边不一致则 CI 失败。',
      '用 Fastlane 以代码方式在 Play Console 创建内购商品和分国家定价。',
    ],
    toolsLabel: '工具箱',
    tools: [
      ['移动端', 'Flutter（GetX、Provider、BLoC）、SwiftUI、WidgetKit、Screen Time API'],
      ['后端', 'Go（net/http、chi、pgx）、Node/Express、Cloudflare Workers'],
      ['数据', 'PostgreSQL、SQLite/SQLCipher、Firestore、Supabase、MongoDB、D1/KV'],
      ['支付', 'StoreKit 2、App Store Server Notifications v2、Google Play Billing'],
      ['发布', 'XcodeGen、Fastlane、自写审计脚本、Fly.io、Render、Docker'],
    ],
  },
}

export const extra: Record<Lang, { caption: string; techLabel: string; lifeLabel: string; life: string[] }> = {
  vi: { caption: 'Đà Nẵng, 2026', techLabel: 'Kỹ thuật', lifeLabel: 'Ngoài giờ', life: ['Biển Đà Nẵng, một buổi chiều mưa', 'Dạo phố ở Thượng Hải', 'Ngồi nghe ở một buổi hội thảo'] },
  en: { caption: 'Da Nang, 2026', techLabel: 'Under the hood', lifeLabel: 'Off hours', life: ['Da Nang beach on a rainy afternoon', 'Wandering around Shanghai', 'Listening in at a conference'] },
  zh: { caption: '岘港，2026', techLabel: '技术细节', lifeLabel: '工作之外', life: ['雨天下午的岘港海边', '在上海逛街', '在一场会议上听讲'] },
}
